name: NewHubSpokeBicepDeploy
env:
  subscriptionId: ${{ secrets.SUB_SANDBOX_2 }}
  azureRegion: East US 2
  templateFile: ./New-HubSpoke-Bicep/main.bicep
  parametersFile: ./New-HubSpoke-Bicep/main.parameters.jsonc

# Controls when the workflow will run
on:
  # Workflow will run on upon a commit
  push:
    branches:
      - main
    paths:
      - "New-HubSpoke-Bicep/**.bicep"
      - "New-HubSpoke-Bicep/**.jsonc"

  # Workflow can be triggered manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # log in to Azure using OpenID Connect
      - uses: Azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.subscriptionId }}
      
      - uses: Azure/arm-deploy@v1
        name: Deploy bicep file
        with:
          scope: subscription
          deploymentName: 'Github.Actions-${{ github.workflow }}-${{ github.run_number }}'
          subscriptionId: ${{ env.subscriptionId }}
          region: ${{env.azureRegion }}
          template: ${{env.templateFile }}
          parameters: ${{ env.parametersFile}}